# Generated by Django 5.0.7 on 2024-07-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
